exp_name: tiny_imagenet_vit_tiny_patch16_224
datadir: ./data
savedir: ./results
dataname: tiny_imagenet
num_classes: 200
model_name: vit_tiny_patch16_224
image_size: 224 ##
opt_name: Adam
lr: 0.001
use_scheduler: false
aug_name: default
epochs: 30
batch_size: 32
log_interval: 50
seed: 223