exp_name: tiny_imagenet_efficientnet_b0
datadir: ./data
savedir: ./results
dataname: tiny_imagenet
num_classes: 200
model_name: efficientnet_b0 
image_size: 224 ##
opt_name: Adam
lr: 0.001
use_scheduler: false
aug_name: default
epochs: 30
batch_size: 32
log_interval: 50
seed: 223